// This file was generated by img2gb, DO NOT EDIT

#ifndef _TILEMAP_FONT_H
#define _TILEMAP_FONT_H

extern const UINT8 FONT_TILEMAP[];
#define FONT_TILEMAP_WIDTH 16
#define FONT_TILEMAP_HEIGHT 5


#endif
