// This file was generated by img2gb, DO NOT EDIT

#ifndef _TILESET_FONT_H
#define _TILESET_FONT_H

extern const UINT8 FONT_TILESET[];
#define FONT_TILESET_TILE_COUNT 48

extern const UINT8 FONT_TILESET_BLCK[];
#define FONT_TILESET_BLCK_TILE_COUNT 48

#endif
