// This file was generated by img2gb, DO NOT EDIT

#ifndef _TILEMAP_SCREEN_H
#define _TILEMAP_SCREEN_H

extern const UINT8 TILEMAPSC[];
#define TILEMAPSC_WIDTH 20
#define TILEMAPSC_HEIGHT 18


#endif
