// This file was generated by img2gb, DO NOT EDIT

#ifndef _TILEMAP_SCREEN_NEW_H
#define _TILEMAP_SCREEN_NEW_H

extern const UINT8 TILEMAPSC_NEW[];
#define TILEMAPSC_NEW_WIDTH 20
#define TILEMAPSC_NEW_HEIGHT 18


#endif
