// This file was generated by img2gb, DO NOT EDIT

#ifndef _KITCHENMAP_H
#define _KITCHENMAP_H

extern const UINT8 TILEMAP_KITCHEN[];
#define TILEMAP_KITCHEN_WIDTH 20
#define TILEMAP_KITCHEN_HEIGHT 18


#endif
