// This file was generated by img2gb, DO NOT EDIT

#ifndef _TITLEMAPSCREEN_H
#define _TITLEMAPSCREEN_H

extern const UINT8 TILEMAP_SCREEN[];
#define TILEMAP_SCREEN_WIDTH 20
#define TILEMAP_SCREEN_HEIGHT 18


#endif
